# JooseMM config file



[window]
padding			= { x = 20, y = 15 }
opacity			= 0.85


[colors]
[colors.primary]	
foreground		= "#fbf1c7"
background		= "#1d2021"
[colors.normal]
black			= "#282828"
red			= "#cc241d"
green			= "#b8bb26"
yellow			= "#d79921"
blue			= "#83a598"
magenta			= "#689d6a"
cyan			= "#fe8019"
white			= "#fbf1c7"

[font]
normal 			= { family = "FiraCode Nerd Font Propo", style = "medium" }
italic 			= { family = "FiraCode Nerd Font Propo", style = "medium" }
size 			= 14


[cursor]
[cursor.style]
shape			= "Block"
blinking		= "Always"

[mouse]
hide_when_typing	= true 
